name: "Baseprinter Action"
description: |
  Generate HTML/PDF previews of Baseprint document snapshot and deploy to GitHub Pages.
inputs:
  xargs-input:
    description: "xargs input file of baseprinter arguments"
    default: "baseprinter-xargs.txt"
  baseprint-path:
    description: "Path to generated baseprint snapshot contents"
    default: "baseprint"
runs:
  using: 'composite'
  steps:
    - name: "Checkout source"
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: "Prepare autobaseprint branch"
      shell: bash
      run: |
        git config user.name  "Baseprinter Action Bot"
        git config user.email "<>"
        git fetch origin autobaseprint || git branch autobaseprint
        git switch autobaseprint
        git log -1 --format=%H
        git merge --no-commit $GITHUB_REF_NAME
        git status
        rm -rf ${{ inputs.baseprint-path }} 
    - name: "Generate HTML/PDF previews of Baseprint document snapshot"
      uses: docker://registry.gitlab.com/perm.pub/dock/baseprinter:25103-53f
      with:
        args: xargs --arg-file ${{ inputs.xargs-input }} baseprinter
    - name: "Commit generated baseprint"
      shell: bash
      run: |
        git add ${{ inputs.baseprint-path }}
        git commit -m "generated baseprint snapshot"
        git push origin autobaseprint
