name: "Baseprinter Action"
description: |
  Generate Baseprint document snapshot contents and commit to autobaseprint branch.
inputs:
  just-recipe:
    description: "just recipe"
    default: "baseprint"
  baseprint-path:
    description: "Path to generated baseprint snapshot contents"
    default: "baseprint"
runs:
  using: 'composite'
  steps:
    - name: "Checkout source"
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: "Prepare autobaseprint branch"
      shell: bash
      run: |
        git config user.name  "Baseprinter Action Bot"
        git config user.email "<>"
        git fetch origin autobaseprint || git branch autobaseprint
        git switch autobaseprint
        git log -1 --format=%H
        git merge --no-commit $GITHUB_REF_NAME
        git status
        rm -rf ${{ inputs.baseprint-path }} 
    - name: "Generate HTML/PDF previews of Baseprint document snapshot"
      uses: docker://registry.gitlab.com/perm.pub/dock/baseprinter:25317-1ef
      with:
        args: just ${{ inputs.just-recipe }}
    - name: "Commit generated baseprint"
      shell: bash
      run: |
        git add -f ${{ inputs.baseprint-path }}
        git commit -m "generated baseprint snapshot"
        git push origin autobaseprint
